name: DevSecOps Pipeline with OWASP Benchmark
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
      - name: Build with Maven
        run: mvn clean install
        
  security_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://localhost:8080/benchmark'
      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
